version: "3.8"

services:
  mongodb:
    container_name: mongodb
    restart: always
    environment:
      MONGODB_DATABASE: notification_service
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"