server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

inventory:
  url: http://localhost:8082